#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias -g P="| "
alias -g PP="pbpaste | "
alias -g C="| pbcopy"
alias -g N="| /dev/null"
alias -g G='| grep'
alias -g L='| bat'
alias -g J='| jq'
alias -g T="| column -t -s $'\t'"

alias tm='tmux'
alias em='emacs -nw'
alias emc='emacsclient -nw'
alias e.='e .'
alias f=ranger

source awsp_functions.sh
alias awsall="_awsListProfile"
alias awsp="_awsSetProfile"
alias awswho="aws configure list"

source /usr/bin/aws_zsh_completer.sh

echo "\n"

#catimg -w 70 /home/arinal/pictures/arch.png
#echo "\n"
#neofetch

figlet -f 3d "Don't use" P lolcat
echo "\n"
figlet -f Bloody "mouse" P lolcat
#figlet -f Elite "Don't use" P lolcat
#figlet -f Banner3-D "mouse" P lolcat
#figlet -f Impossible "mouse" P lolcat
